### ISSUE TITLE
Failed installing web UI

### ISSUE THREAD

**Issue by Playfullycat** [sockeye44/instavpn#52]
23:17:15 INFO: Installing web UI...
23:17:16 CRITICAL: Failed installing web UI
CRITICAL ERROR!
Failed installing web UI

**Comment by sockeye44** [comment]
Hello. Could you provide log entries after this lines?
e.g. Crash report: https://...

**Comment by logs777** [comment]
Hello! First of all - thanks a lot for simple and fast-to-deploy solution!!!
I had the same error during installation ( I solved it), may be author of this issue had another problem, but in my case the problem was in folder '/opt', which was created by default in my VPS.
I found this problem in log https://pastee.org/fwnc9 
May be script should check existence of folder?

**Comment by logs777** [comment]
e.g. in bash:
...
if [ -d /opt ]; then : ; else
                echo 'Folder /opt doesn't exist and will be created'
                mkdir /opt
...

**Comment by sockeye44** [comment]
Fixed. Thank you
